### ISSUE TITLE
KEGG drugs associated with kegg.compound MIRIAM data collection

### ISSUE THREAD

**Issue by matthiaskoenig** [SBRG/ModelPolisher#13] opened 2016-08-10 07:44 UTC
Hi all,

KEGG Drugs are associated with the wrong collection in `e_coli_core`, probably also in other models.
They use `kegg.compound` (http://www.ebi.ac.uk/miriam/main/collections/MIR:00000013) but should use `kegg.drug` (http://www.ebi.ac.uk/miriam/main/collections)/MIR:00000025.

Examples from e_coli_core:

```
07:58:02 WARN  [Thread-34]  org.cy3sbml.gui.SBaseHTMLFactory - Identifier <D00001> does not match pattern <^C\d+$> of data collection: <MIR:00000013>
07:58:02 WARN  [Thread-34]  org.cy3sbml.gui.SBaseHTMLFactory - Identifier <D03703> does not match pattern <^C\d+$> of data collection: <MIR:00000013>
07:58:02 WARN  [Thread-34]  org.cy3sbml.gui.SBaseHTMLFactory - Identifier <D06322> does not match pattern <^C\d+$> of data collection: <MIR:00000013>
```

The best
Matthias

**Comment by draeger** [comment] 2016-11-23 20:13
This is also interesting for @zakandrewking:

ModelPolisher pulls resource URIs directly from BiGG database using this code in class `BiGGDB`:
```java
  private List<String> getResourceURL(BiGGId biggId, String type,
    boolean includeAnyURI) throws SQLException {
    ResultSet rst = connect.query(
      "SELECT CONCAT(" + BiGGDBContract.Constants.URL_PREFIX + ", "
        + BiGGDBContract.Constants.S_SYNONYM + ") AS "
        + BiGGDBContract.Constants.URL + " " + "FROM  %s c, "
        + BiGGDBContract.Constants.SYNONYM + ", "
        + BiGGDBContract.Constants.DATA_SOURCE + " " + "WHERE "
        + BiGGDBContract.Constants.C_ID + " = "
        + BiGGDBContract.Constants.S_OME_ID + " AND" + "      "
        + BiGGDBContract.Constants.S_DATA_SOURCE_ID + " = "
        + BiGGDBContract.Constants.D_ID + " AND" + "      "
        + BiGGDBContract.Constants.URL_PREFIX + " IS NOT NULL AND" + "      "
        + BiGGDBContract.Constants.C_BIGG_ID + " = '%s'%s",
      type, biggId.getAbbreviation(), includeAnyURI ? "" : " AND "
        + BiGGDBContract.Constants.URL_PREFIX + " like '%%identifiers.org%%'");
    List<String> result = new LinkedList<String>();
    while (rst.next()) {
      result.add(rst.getString(1));
    }
    rst.getStatement().close();
    return result;
  }`

So, the URI is entirely built from the content of the database. While an additional correctness check would be possible and would also make sense at this point (in particular since ModelPolisher already contains many relevant catalog patterns in its class `MIRIAM`), this is still primarily a problem of BiGG database and should be fixed there in the first place.

We will investigate how to automatically correct wrong catalogs when fetching this information from BiGG as well.

**Comment by zakandrewking** [comment] 2016-12-09 18:35
I can confirm this, so I added an issue to BiGG Models. Feel free to close this one.

**Comment by draeger** [comment] 2016-12-09 19:44
Thanks! I leave it open until we have implemented a better pattern matching for ids in MIRIAM catalogues.

**Comment by mephenor** [comment] 2017-01-07 19:20
kegg.glycan entries are also associated with kegg.compound. Adding a check to ModelPolisher to change the collection based on the KEGG indentifier for both cases.

**Closed** 2017-01-07 19:34 UTC
Labels: bug
